### PR TITLE
Docs readability improvements

### PR DESCRIPTION
**Pull request by ncordon**
Some typos and grammar corrections. This includes changes for the [gRPC usage example](https://doc.bblf.sh/using-babelfish/grpc-usage-example.html) which is outdated #227 

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/documentation/265)

### CODE REVIEW

**Comment by ncordon** [comment]
> Please rebase instead of merging `master` into the dev branch.
Done!

**Comment by ncordon** [comment]
___
*[using-babelfish/grpc-usage-example.md, line 62 at r1](https://reviewable.io/reviews/bblfsh/documentation/265#-LjGg9_-DJjCYtjmIoH5:-LjMkmZ56n66QgkticCV:bxlr2ub) ([raw file](https://github.com/bblfsh/documentation/blob/142e49e87193f3af8c8f941a94d3e7f6851a49b9/using-babelfish/grpc-usage-example.md#L62)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Should be either "children nodes" or "node's children"
</blockquote></details>

True, changed now

**Comment by bzz** [comment]
@ncordon it seems like DCO sign-off is missing from 61eaf526f6a7ee24d16178faf50bc650ec5342ac

**Comment by ncordon** [comment]
> @ncordon it seems like DCO sign-off is missing from [61eaf52](https://github.com/bblfsh/documentation/commit/61eaf526f6a7ee24d16178faf50bc650ec5342ac)

Not the first time it has happened to me :see_no_evil:

**Pull request merged**
