### PR TITLE
use docker volumes to keep installed drivers

### PR DESCRIPTION
**Pull request by campoy**

### CODE REVIEW

**Comment by juanjux** [comment]
Thanks for the PR! Could you try this with the Python driver? (it was the one that gave us problems with duplicated files with different casing).

**Comment by juanjux** [comment]
CC @campoy  (I would test this myself but I'm not using a mac).

**Comment by juanjux** [comment]
Tested, works.

**Comment by smacker** [comment]
btw you don't really need `docker volume create bblfshd-cache`, docker will create it during `run`. But it's okay to have it in docs for better understanding what is going on.

**Pull request merged**
